tap "jesseduffield/lazydocker"
tap "kdash-rs/kdash"
tap "stablyai/orca"
tap "vmware-tanzu/carvel"

brew "argocd"
brew "ansible"
brew "ansible-lint"
brew "awk"
brew "bash"
brew "bat"
brew "clair"
brew "coreutils"
brew "cosign"
brew "curl"
brew "delve"
brew "direnv"
brew "dive"
brew "eza"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "grep"
brew "htop"
brew "ipcalc"
brew "iperf3"
brew "istioctl"
brew "k3d"
brew "k9s"
brew "kcat"
brew "kdash"
brew "kubernetes-cli", link: false
brew "kubie"
brew "lazydocker"
brew "lazygit"
brew "lychee"
brew "make"
brew "mise"
brew "moreutils"
brew "nano"
brew "nanorc"
brew "ngrep"
brew "nmap"
brew "nushell"
brew "pipx"
brew "plantuml"
brew "qemu"
brew "qpdf"
brew "rancher-cli"
brew "rclone"
brew "restic"
brew "resticprofile"
brew "ripgrep"
brew "rsync"
brew "rust"
brew "slides"
brew "starship"
brew "stern"
brew "stow"
brew "telnet"
brew "tmux"
brew "tree"
brew "vhs"
brew "vim"
brew "virtualenv"
brew "watch"
brew "wget"
brew "wireguard-tools"
brew "xz"
brew "zsh"

# cask "1password"
cask "1password-cli"
# cask "autodesk-fusion"
# cask "balenaetcher"
cask "bambu-studio"
cask "bettertouchtool"
cask "claude"
cask "claude-code"
cask "copilot-cli"
# cask "cursor"
cask "cursor-cli"
# cask "cyberduck"
# cask "dbeaver-community"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-sans"
# cask "firefox"
cask "firefox@developer-edition"
cask "gcloud-cli"
# cask "gimp"
# cask "google-chrome"
# cask "google-chrome@canary"
# cask "gpg-suite"
cask "iterm2"
# cask "joplin"
# cask "logi-options+" # replaced with openlogi
cask "macfuse"
# cask "mqtt-explorer"
cask "ngrok"
cask "openlogi"
cask "opensuperwhisper"
cask "orbstack"
cask "stablyai/orca/orca"
cask "sequel-ace"
cask "slack"
cask "spotify"
cask "syncthing-app"
# cask "tailscale-app"
# cask "teamviewer"
# cask "teamviewer-quickjoin"
# cask "teamviewer-quicksupport"
cask "the-unarchiver"
cask "visual-studio-code"
# cask "vlc"
cask "wireshark-app"
