format = """\
  ${custom.git_user}\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $terraform\
  $fill\
  $time \
  $line_break\
  $directory\
  $character\
"""

command_timeout = 1000

[battery]
charging_symbol = ""
discharging_symbol = ""
full_symbol = ""

[character]
format = "$symbol "
error_symbol = "[✗](red)"
success_symbol = "[»](green)"
vicmd_symbol = "«"

[custom.git_user]
command = "git config user.email"
when = "git -C . rev-parse --is-inside-work-tree &>/dev/null"
format = "[$symbol($output) ]($style)"
shell = ["sh"]
style = "green"
symbol = ""

[directory]
style = "green"
truncate_to_repo = true
truncation_length = 5
fish_style_pwd_dir_length = 1

[docker_context]
symbol = ""

[fill]
symbol = " "
style = ""

[git_branch]
style = "green"
symbol = ""

[golang]
symbol = " "

[kubernetes]
disabled = true
format = '[$symbol$context( \($namespace\))]($style)'
style = "blue"

[kubernetes.context_aliases]

[php]
disabled = true

[terraform]
style = "purple"
symbol = "₸ "

[time]
disabled = false
format = '[$time]($style)'
style = "#a0a0a0"
