prompt_order = [
  "username",
  "hostname",
  "kubernetes",
  "custom.git_user",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "docker_context",
  "terraform",
  "cmd_duration",
  "line_break",
  "username",
  "hostname",
  "directory",
  "battery",
  "time",
  "character",
]

[battery]
charging_symbol = ""
discharging_symbol = ""
full_symbol = ""

[character]
error_symbol = "✗"
style_failure = "red"
style_success = "green"
#symbol = "►"
symbol = "»"
use_symbol_for_status = true
#vicmd_symbol = "◀︎"
vicmd_symbol = "«"

[directory]
style = "green"
truncate_to_repo = true
truncation_length = 5
fish_style_pwd_dir_length = 1

[docker]
symbol = ""

[custom.git_user]
command = "git config user.email"
directories = [".git"]
prefix = ""
shell = ["sh"]
style = "green"

[git_branch]
style = "green"
symbol = " "

[golang]
symbol = " "

[kubernetes]
disabled = false
style = "blue"

[kubernetes.context_aliases]

[php]
disabled = true

[terraform]
style = "purple"
symbol = "₸ "
