#!/usr/bin/env bash
set -eu

# Ask for the administrator password upfront
sudo -v

sudo eopkg install git make curl wget vim tmux xz docker docker-compose \
 kubectl minikube vscode

sudo ln -sf "$(which code-oss)" /usr/local/bin/code

