#!/usr/bin/env bash
set -eu

# Ask for the administrator password upfront
sudo -v

apt-install apt-transport-https build-essential git make curl wget vim tmux xz-utils \
 docker.io docker-compose

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

apt-install kubectl
